namespace Lux.Common
{
  [default_interface]
  runtimeclass DisplayOutputInfo
  {
    UInt64 AdapterId;
    String OutputId;
    String Name;
    
    DisplayOutputInfo();

    static Windows.Foundation.Collections.IVector<DisplayOutputInfo> GetOutputs();
  }
}