namespace Lux
{
  [default_interface]
  runtimeclass MainPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
  {
    MainPage();

    Boolean IsConnected{ get; };
    String ConnectionState{ get; };

    Boolean IsSourceOff{ get; };
    Boolean IsSourceStatic{ get; };
    Boolean IsSourceRainbow{ get; };
    Boolean IsSourceContextAware{ get; };

    void ConfigureDevice();
  }
}
